### PR TITLE
Update to version 0.2.2

### PR DESCRIPTION
**Pull request by jaimeambrus**

### CODE REVIEW

**Comment by jaimeambrus** [comment]
@tadeu Could you please review and possibly merge this? Thanks!

**Comment by tadeu** [comment]
@jaimeambrus, sure, is it ok to also add you as a maintainer?

**Comment by jaimeambrus** [comment]
> 
> 
> @jaimeambrus, sure, is it ok to also add you as a maintainer?

Sure, not a problem.

**Comment by tadeu** [comment]
thanks for these fixes @jaimeambrus

**Comment by tadeu** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
